### ISSUE TITLE
plugin.proto file is not crucial part for wdlc compilation

### ISSUE THREAD

**Issue by yunhanw-google** [openweave/openweave-wdlc#7]
debian libprotobuf-dev contains the development headers and static libraries needed for writing c++ applications, Includes well known proto type files, but the schema/plugin.proto is missing. 
In contrast, in upstream GitHub link(https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip), it has included plugin.proto file.

currently wdlc is checking plugin.proto file for compilation, without it, the compilation would fail. In fact, the wdlc should be compiled without plugin.proto.

Can you remove this plugin.proto check in code?

**Comment by gerickson** [comment]
I'll take a look at effecting a check for a different file.

**Comment by gerickson** [comment]
See https://github.com/openweave/openweave-wdlc/pull/8.
